/*
 * Host-side coverage for the base 5A22 I/O and DMA register images.
 */

#include <cstdio>

#include "types.h"
#include "sndma.h"
#include "snio.h"

static int g_Failures;

static void Check(const char *pName, unsigned uGot, unsigned uExpected)
{
	if (uGot != uExpected)
	{
		std::printf("FAIL %s: %04X != %04X\n", pName, uGot, uExpected);
		g_Failures++;
	}
}

static void CheckPowerOnRegisters()
{
	SnesIO io;

	Check("RDNMI version", io.m_Regs.rdnmi, 0x02);
	Check("WRIO power-on", io.m_Regs.wrio, 0xFF);
	Check("HTIME power-on", io.m_Regs.htime.w, 0x01FF);
	Check("VTIME power-on", io.m_Regs.vtime.w, 0x01FF);
	Check("WRMPYA power-on", io.m_Regs.wrmpya, 0xFF);
	Check("WRDIV power-on", io.m_Regs.wrdiv.w, 0xFFFF);

	io.m_Regs.wrio = 0;
	io.m_Regs.htime.w = 0;
	io.m_Regs.vtime.w = 0;
	io.Reset();
	Check("WRIO reset", io.m_Regs.wrio, 0xFF);
	Check("HTIME reset", io.m_Regs.htime.w, 0x01FF);
	Check("VTIME reset", io.m_Regs.vtime.w, 0x01FF);
}


static void CheckTimedALU()
{
	SnesIO io;
	SNCpuT cpu = {};

	/* $80 * 3 needs the eighth shift/add step; this makes the read-phase
	   boundary visible instead of accidentally reaching the final result early. */
	cpu.uCpuCycleCount = 1;
	io.WriteALU(&cpu, 0x4202, 0x80);
	cpu.uCpuCycleCount = 2;
	io.WriteALU(&cpu, 0x4203, 0x03);

	cpu.uCpuCycleCount = 10; /* read samples cycle 9: seven ALU steps elapsed */
	Check("multiply before eighth step L", io.ReadALU(&cpu, 0x4216), 0x00);
	Check("multiply before eighth step H", io.ReadALU(&cpu, 0x4217), 0x00);
	cpu.uCpuCycleCount = 11; /* read samples cycle 10: eighth step is complete */
	Check("multiply after eight steps L", io.ReadALU(&cpu, 0x4216), 0x80);
	Check("multiply after eight steps H", io.ReadALU(&cpu, 0x4217), 0x01);

	/* 1000 / 7 exposes an intermediate quotient of 71 after 15 steps. */
	io.Reset();
	cpu.uCpuCycleCount = 1;
	io.WriteALU(&cpu, 0x4204, 0xE8);
	cpu.uCpuCycleCount = 2;
	io.WriteALU(&cpu, 0x4205, 0x03);
	cpu.uCpuCycleCount = 3;
	io.WriteALU(&cpu, 0x4206, 0x07);
	cpu.uCpuCycleCount = 19; /* read phase = 18 => 15 division steps */
	Check("divide step 15 quotient L", io.ReadALU(&cpu, 0x4214), 71);
	Check("divide step 15 remainder L", io.ReadALU(&cpu, 0x4216), 6);
	cpu.uCpuCycleCount = 20; /* read phase = 19 => all 16 steps */
	Check("divide result quotient L", io.ReadALU(&cpu, 0x4214), 142);
	Check("divide result quotient H", io.ReadALU(&cpu, 0x4215), 0);
	Check("divide result remainder", io.ReadALU(&cpu, 0x4216), 6);

	/* Division by zero is generated by the same 16-step divider. */
	io.Reset();
	cpu.uCpuCycleCount = 1;
	io.WriteALU(&cpu, 0x4204, 0x34);
	cpu.uCpuCycleCount = 2;
	io.WriteALU(&cpu, 0x4205, 0x12);
	cpu.uCpuCycleCount = 3;
	io.WriteALU(&cpu, 0x4206, 0x00);
	cpu.uCpuCycleCount = 20;
	Check("divide by zero quotient L", io.ReadALU(&cpu, 0x4214), 0xFF);
	Check("divide by zero quotient H", io.ReadALU(&cpu, 0x4215), 0xFF);
	Check("divide by zero remainder L", io.ReadALU(&cpu, 0x4216), 0x34);
	Check("divide by zero remainder H", io.ReadALU(&cpu, 0x4217), 0x12);

	/* A write whose read phase still sees the old multiply is blocked even
	   if the final ALU step finishes at that write's write phase. */
	io.Reset();
	cpu.uCpuCycleCount = 1;
	io.WriteALU(&cpu, 0x4202, 0x80);
	cpu.uCpuCycleCount = 2;
	io.WriteALU(&cpu, 0x4203, 0x03);
	cpu.uCpuCycleCount = 10; /* old op finishes in this write phase */
	io.WriteALU(&cpu, 0x4203, 0x04);
	cpu.uCpuCycleCount = 30;
	Check("last-cycle multiply write blocked result", io.ReadALU(&cpu, 0x4216), 0);
	Check("last-cycle multiply write keeps loaded shift L", io.ReadALU(&cpu, 0x4214), 0x80);
	Check("last-cycle multiply write keeps loaded shift H", io.ReadALU(&cpu, 0x4215), 0x04);
}

static void CheckAutoJoypadTiming()
{
	SnesIO io;
	Emu::SysInputT input = {};

	input.uPad[0] = 0xA5F0;
	input.uPad[1] = 0x3C70;
	input.uPad[2] = EMUSYS_DEVICE_DISCONNECTED;
	input.uPad[3] = EMUSYS_DEVICE_DISCONNECTED;
	input.uPad[4] = EMUSYS_DEVICE_DISCONNECTED;
	io.LatchInput(&input);
	io.m_Regs.nmitimen = 0x01;

	/* With a frame/VBlank reference clock of 1000, the aligned sequencer
	   begins at 1152. Busy becomes visible one 128-clock phase later. */
	io.BeginAutoJoypad(1000);
	io.ProcessAutoJoypad(1279);
	Check("autojoy busy before step1", io.IsAutoJoypadActive(), 0);
	io.ProcessAutoJoypad(1280);
	Check("autojoy busy at step1", io.IsAutoJoypadActive(), 1);
	Check("autojoy joy1 cleared at start", io.m_Regs.joy1.w, 0);
	io.ProcessAutoJoypad(5504);
	Check("autojoy busy after step34", io.IsAutoJoypadActive(), 0);
	Check("autojoy joy1 result", io.m_Regs.joy1.w, 0xA5F0);
	Check("autojoy joy2 result", io.m_Regs.joy2.w, 0x3C70);

	/* Changing enable during the opening 256 clocks immediately changes
	   OUT0 and prevents this frame's transfer from becoming active. */
	io.Reset();
	io.LatchInput(&input);
	io.m_Regs.nmitimen = 0x01;
	io.BeginAutoJoypad(1000);
	io.ProcessAutoJoypad(1152);
	Check("autojoy strobe high", io.m_Regs.joydata & 1, 1);
	io.PrepareAutoJoypadEnableChange(1200, FALSE);
	io.m_Regs.nmitimen &= (Uint8)~0x01;
	Check("autojoy strobe follows disable", io.m_Regs.joydata & 1, 0);
	io.ProcessAutoJoypad(1280);
	Check("autojoy disabled before busy", io.IsAutoJoypadActive(), 0);
}

static void CheckDMATimingMath()
{
	/* MesenCE aligns DMA ownership to the next multiple of 8 master clocks. */
	Check("DMA start sync @0", SnesDMAC::CalcStartSync(0), 8);
	Check("DMA start sync @2", SnesDMAC::CalcStartSync(2), 6);
	Check("DMA start sync @6", SnesDMAC::CalcStartSync(6), 2);
	Check("DMA start sync @8", SnesDMAC::CalcStartSync(8), 8);

	/* DMA resumes on the next boundary of the CPU clock that was paused. */
	Check("DMA end sync slow aligned", SnesDMAC::CalcEndSync(16, 8), 8);
	Check("DMA end sync slow +2", SnesDMAC::CalcEndSync(18, 8), 6);
	Check("DMA end sync fast +2", SnesDMAC::CalcEndSync(14, 6), 4);
	Check("DMA end sync xslow +4", SnesDMAC::CalcEndSync(20, 12), 4);
}

static void CheckDMARegisterMap()
{
	SnesDMAC dma;
	unsigned uChannel;

	dma.Reset();
	for (uChannel = 0; uChannel < SNESDMAC_CHANNEL_NUM; uChannel++)
	{
		unsigned uOffset;
		for (uOffset = 0; uOffset <= 0x0A; uOffset++)
			Check("DMA power-on register", dma.Read8(uChannel, uOffset, 0x43),
			      0xFF);
		Check("DMA $43xB power-on", dma.Read8(uChannel, 0x0B, 0x43), 0xFF);
		Check("DMA $43xF mirror", dma.Read8(uChannel, 0x0F, 0x43), 0xFF);
		Check("DMA $43xC open bus", dma.Read8(uChannel, 0x0C, 0x43), 0x43);
		Check("DMA $43xD open bus", dma.Read8(uChannel, 0x0D, 0x43), 0x43);
		Check("DMA $43xE open bus", dma.Read8(uChannel, 0x0E, 0x43), 0x43);

		for (uOffset = 0; uOffset <= 0x0B; uOffset++)
			dma.Write8(uChannel, uOffset,
			           (Uint8)(0x10u * uChannel + uOffset));
		for (uOffset = 0; uOffset <= 0x0B; uOffset++)
			Check("DMA register round trip", dma.Read8(uChannel, uOffset, 0x43),
			      0x10u * uChannel + uOffset);
		Check("DMA $43xB/$43xF storage mirror",
		      dma.Read8(uChannel, 0x0F, 0x43), 0x10u * uChannel + 0x0B);
	}
}

int main()
{
	CheckPowerOnRegisters();
	CheckTimedALU();
	CheckAutoJoypadTiming();
	CheckDMATimingMath();
	CheckDMARegisterMap();

	if (g_Failures)
	{
		std::printf("%d I/O register test(s) failed\n", g_Failures);
		return 1;
	}

	std::puts("I/O register tests passed");
	return 0;
}
