/*
 * Host-side coverage for the base 5A22 I/O and DMA register images.
 */

#include <cstdio>

#include "types.h"
#include "sndma.h"
#include "snio.h"
#include "sntiming.h"

static int g_Failures;

static void Check(const char *pName, unsigned uGot, unsigned uExpected)
{
	if (uGot != uExpected)
	{
		std::printf("FAIL %s: %04X != %04X\n", pName, uGot, uExpected);
		g_Failures++;
	}
}

static void CheckPowerOnRegisters()
{
	SnesIO io;

	Check("RDNMI version", io.m_Regs.rdnmi, 0x02);
	Check("WRIO power-on", io.m_Regs.wrio, 0xFF);
	Check("HTIME power-on", io.m_Regs.htime.w, 0x01FF);
	Check("VTIME power-on", io.m_Regs.vtime.w, 0x01FF);
	Check("WRMPYA power-on", io.m_Regs.wrmpya, 0xFF);
	Check("WRDIV power-on", io.m_Regs.wrdiv.w, 0xFFFF);

	io.m_Regs.wrio = 0;
	io.m_Regs.htime.w = 0;
	io.m_Regs.vtime.w = 0;
	io.Reset();
	Check("WRIO reset", io.m_Regs.wrio, 0xFF);
	Check("HTIME reset", io.m_Regs.htime.w, 0x01FF);
	Check("VTIME reset", io.m_Regs.vtime.w, 0x01FF);
}


static void CheckTimedALU()
{
	SnesIO io;
	SNCpuT cpu = {};

	/* $80 * 3 needs the eighth shift/add step; this makes the read-phase
	   boundary visible instead of accidentally reaching the final result early. */
	cpu.uCpuCycleCount = 1;
	io.WriteALU(&cpu, 0x4202, 0x80);
	cpu.uCpuCycleCount = 2;
	io.WriteALU(&cpu, 0x4203, 0x03);

	cpu.uCpuCycleCount = 10; /* read samples cycle 9: seven ALU steps elapsed */
	Check("multiply before eighth step L", io.ReadALU(&cpu, 0x4216), 0x00);
	Check("multiply before eighth step H", io.ReadALU(&cpu, 0x4217), 0x00);
	cpu.uCpuCycleCount = 11; /* read samples cycle 10: eighth step is complete */
	Check("multiply after eight steps L", io.ReadALU(&cpu, 0x4216), 0x80);
	Check("multiply after eight steps H", io.ReadALU(&cpu, 0x4217), 0x01);

	/* 1000 / 7 exposes an intermediate quotient of 71 after 15 steps. */
	io.Reset();
	cpu.uCpuCycleCount = 1;
	io.WriteALU(&cpu, 0x4204, 0xE8);
	cpu.uCpuCycleCount = 2;
	io.WriteALU(&cpu, 0x4205, 0x03);
	cpu.uCpuCycleCount = 3;
	io.WriteALU(&cpu, 0x4206, 0x07);
	cpu.uCpuCycleCount = 19; /* read phase = 18 => 15 division steps */
	Check("divide step 15 quotient L", io.ReadALU(&cpu, 0x4214), 71);
	Check("divide step 15 remainder L", io.ReadALU(&cpu, 0x4216), 6);
	cpu.uCpuCycleCount = 20; /* read phase = 19 => all 16 steps */
	Check("divide result quotient L", io.ReadALU(&cpu, 0x4214), 142);
	Check("divide result quotient H", io.ReadALU(&cpu, 0x4215), 0);
	Check("divide result remainder", io.ReadALU(&cpu, 0x4216), 6);

	/* Division by zero is generated by the same 16-step divider. */
	io.Reset();
	cpu.uCpuCycleCount = 1;
	io.WriteALU(&cpu, 0x4204, 0x34);
	cpu.uCpuCycleCount = 2;
	io.WriteALU(&cpu, 0x4205, 0x12);
	cpu.uCpuCycleCount = 3;
	io.WriteALU(&cpu, 0x4206, 0x00);
	cpu.uCpuCycleCount = 20;
	Check("divide by zero quotient L", io.ReadALU(&cpu, 0x4214), 0xFF);
	Check("divide by zero quotient H", io.ReadALU(&cpu, 0x4215), 0xFF);
	Check("divide by zero remainder L", io.ReadALU(&cpu, 0x4216), 0x34);
	Check("divide by zero remainder H", io.ReadALU(&cpu, 0x4217), 0x12);

	/* A write whose read phase still sees the old multiply is blocked even
	   if the final ALU step finishes at that write's write phase. */
	io.Reset();
	cpu.uCpuCycleCount = 1;
	io.WriteALU(&cpu, 0x4202, 0x80);
	cpu.uCpuCycleCount = 2;
	io.WriteALU(&cpu, 0x4203, 0x03);
	cpu.uCpuCycleCount = 10; /* old op finishes in this write phase */
	io.WriteALU(&cpu, 0x4203, 0x04);
	cpu.uCpuCycleCount = 30;
	Check("last-cycle multiply write blocked result", io.ReadALU(&cpu, 0x4216), 0);
	Check("last-cycle multiply write keeps loaded shift L", io.ReadALU(&cpu, 0x4214), 0x80);
	Check("last-cycle multiply write keeps loaded shift H", io.ReadALU(&cpu, 0x4215), 0x04);
}

static void CheckAutoJoypadTiming()
{
	SnesIO io;
	Emu::SysInputT input = {};

	input.uPad[0] = 0xA5F0;
	input.uPad[1] = 0x3C70;
	input.uPad[2] = EMUSYS_DEVICE_DISCONNECTED;
	input.uPad[3] = EMUSYS_DEVICE_DISCONNECTED;
	input.uPad[4] = EMUSYS_DEVICE_DISCONNECTED;
	io.LatchInput(&input);
	io.m_Regs.nmitimen = 0x01;

	/* With a frame/VBlank reference clock of 1000, the aligned sequencer
	   begins at 1152. Busy becomes visible one 128-clock phase later. */
	io.BeginAutoJoypad(1000);
	io.ProcessAutoJoypad(1279);
	Check("autojoy busy before step1", io.IsAutoJoypadActive(), 0);
	io.ProcessAutoJoypad(1280);
	Check("autojoy busy at step1", io.IsAutoJoypadActive(), 1);
	Check("autojoy joy1 cleared at start", io.m_Regs.joy1.w, 0);
	io.ProcessAutoJoypad(5504);
	Check("autojoy busy after step34", io.IsAutoJoypadActive(), 0);
	Check("autojoy joy1 result", io.m_Regs.joy1.w, 0xA5F0);
	Check("autojoy joy2 result", io.m_Regs.joy2.w, 0x3C70);

	/* Changing enable during the opening 256 clocks immediately changes
	   OUT0 and prevents this frame's transfer from becoming active. */
	io.Reset();
	io.LatchInput(&input);
	io.m_Regs.nmitimen = 0x01;
	io.BeginAutoJoypad(1000);
	io.ProcessAutoJoypad(1152);
	Check("autojoy strobe high", io.m_Regs.joydata & 1, 1);
	io.PrepareAutoJoypadEnableChange(1200, FALSE);
	io.m_Regs.nmitimen &= (Uint8)~0x01;
	Check("autojoy strobe follows disable", io.m_Regs.joydata & 1, 0);
	io.ProcessAutoJoypad(1280);
	Check("autojoy disabled before busy", io.IsAutoJoypadActive(), 0);
}

static Uint32 ReadSerialBits0(SnesIO &io, int nBits)
{
	Uint32 uValue = 0;
	while (nBits-- > 0)
		uValue = (uValue << 1) | (io.ReadSerial0() & 1);
	return uValue;
}

static Uint32 ReadSerialBits1(SnesIO &io, int nBits)
{
	Uint32 uValue = 0;
	while (nBits-- > 0)
		uValue = (uValue << 1) | (io.ReadSerial1() & 1);
	return uValue;
}

static void CheckSpecialPeripherals()
{
	SnesIO io;
	Emu::SysInputT input = {};

	for (int i=0; i<EMUSYS_DEVICE_NUM; i++)
		input.uPad[i] = EMUSYS_DEVICE_DISCONNECTED;

	/* SNES Mouse: 00, status, Y, X; MSB first. Negative motion uses
	   sign-and-magnitude and official hardware returns ones after bit 32. */
	input.uPad[4] = EMUSYS_SNES_SPECIAL_MOUSE;
	input.uPad[2] = (Uint16)0xFB | ((Uint16)0x07 << 8); /* X=-5, Y=+7 */
	input.uPad[3] = EMUSYS_SNES_MOUSE_LEFT | EMUSYS_SNES_MOUSE_RIGHT;
	io.LatchInput(&input);
	io.WriteSerial(1);
	io.WriteSerial(0);
	Check("mouse 32-bit report", ReadSerialBits0(io, 32), 0x00C10785u);
	Check("mouse post-report one", io.ReadSerial0() & 1, 1);

	/* Clocking while OUT0 is high cycles 0 -> 1 sensitivity. */
	io.WriteSerial(1);
	(void)io.ReadSerial0();
	io.WriteSerial(0);
	Check("mouse sensitivity status", ReadSerialBits0(io, 16), 0x00D1);

	/* Super Scope occupies port 2 and reports FCTP00nN + $FF. */
	io.Reset();
	for (int i=0; i<EMUSYS_DEVICE_NUM; i++)
		input.uPad[i] = EMUSYS_DEVICE_DISCONNECTED;
	input.uPad[4] = EMUSYS_SNES_SPECIAL_SUPERSCOPE;
	input.uPad[2] = 123u | (77u << 8);
	input.uPad[3] =
		EMUSYS_SNES_SCOPE_FIRE |
		EMUSYS_SNES_SCOPE_CURSOR |
		EMUSYS_SNES_SCOPE_TURBO |
		EMUSYS_SNES_SCOPE_PAUSE;
	io.LatchInput(&input);
	io.WriteSerial(1);
	io.WriteSerial(0);
	Check("scope 16-bit report", ReadSerialBits1(io, 16), 0xF0FF);

	Uint16 uX = 0, uY = 0;
	Check("scope position present", io.GetSuperScopePosition(&uX, &uY), 1);
	Check("scope X", uX, 123);
	Check("scope Y", uY, 77);

	/* Single Konami Justifier: falling OUT0 selects the absent second gun,
	   and the 32-bit stream reports signature/buttons/active selector. */
	io.Reset();
	for (int i=0; i<EMUSYS_DEVICE_NUM; i++)
		input.uPad[i] = EMUSYS_DEVICE_DISCONNECTED;
	input.uPad[4] = EMUSYS_SNES_SPECIAL_JUSTIFIER;
	input.uPad[2] = 45u | (67u << 8);
	input.uPad[1] = (Uint16)(0xFFF0u |
		EMUSYS_SNES_JUSTIFIER1_TRIGGER |
		EMUSYS_SNES_JUSTIFIER1_START);
	io.LatchInput(&input);
	io.WriteSerial(1);
	io.WriteSerial(0);
	Check("justifier single active1 report",
	      ReadSerialBits1(io, 32), 0x000E55A8u);
	Check("justifier single active1 has no gun",
	      io.GetJustifierPosition(&uX, &uY), 0);
	Check("justifier post-report one", io.ReadSerial1() & 1, 1);

	/* Next falling edge selects gun 1 again. */
	io.WriteSerial(1);
	io.WriteSerial(0);
	Check("justifier single active0 report",
	      ReadSerialBits1(io, 32), 0x000E55A0u);
	Check("justifier single gun1 present",
	      io.GetJustifierPosition(&uX, &uY), 1);
	Check("justifier gun1 X", uX, 45);
	Check("justifier gun1 Y", uY, 67);

	/* Chained pair exposes player 2 when active=1 and adds its button bits. */
	io.Reset();
	for (int i=0; i<EMUSYS_DEVICE_NUM; i++)
		input.uPad[i] = EMUSYS_DEVICE_DISCONNECTED;
	input.uPad[4] = EMUSYS_SNES_SPECIAL_JUSTIFIERS;
	input.uPad[2] = 10u | (20u << 8);
	input.uPad[3] = 30u | (40u << 8);
	input.uPad[1] = (Uint16)(0xFFF0u |
		EMUSYS_SNES_JUSTIFIER1_TRIGGER |
		EMUSYS_SNES_JUSTIFIER1_START |
		EMUSYS_SNES_JUSTIFIER2_TRIGGER |
		EMUSYS_SNES_JUSTIFIER2_START);
	io.LatchInput(&input);
	io.WriteSerial(1);
	io.WriteSerial(0);
	Check("justifiers dual active1 report",
	      ReadSerialBits1(io, 32), 0x000E55F8u);
	Check("justifiers gun2 present", io.GetJustifierPosition(&uX, &uY), 1);
	Check("justifiers gun2 X", uX, 30);
	Check("justifiers gun2 Y", uY, 40);
}

static void CheckScanlineTiming()
{
	Check("normal even-field line", SNES_LINE_MASTER_CYCLES(240, FALSE, FALSE), 1364);
	Check("odd non-interlace line 240", SNES_LINE_MASTER_CYCLES(240, TRUE, FALSE), 1360);
	Check("odd line 239 remains normal", SNES_LINE_MASTER_CYCLES(239, TRUE, FALSE), 1364);
	Check("interlace odd line 240 remains normal", SNES_LINE_MASTER_CYCLES(240, TRUE, TRUE), 1364);
	Check("HBlank start clock", SNES_HBLANK_START_CYCLES, 1096);
	Check("HDMA start clock", SNES_HDMA_START_CYCLES, 1104);
	Check("HDMA starts 8 clocks after HBlank",
	      SNES_HDMA_START_CYCLES - SNES_HBLANK_START_CYCLES, 8);
	Check("software visible slice ends before HBlank",
	      SNES_VISIBLE_CYCLES < SNES_HBLANK_START_CYCLES, 1);

	/* ares models the Super Scope optical hit 24 dots after the aimed X.
	   Verify both active-display and late-HBlank positions. */
	Check("scope x0 beam clock", SNES_SUPERSCOPE_LATCH_CYCLES(0), 96);
	Check("scope x128 beam clock", SNES_SUPERSCOPE_LATCH_CYCLES(128), 608);
	Check("scope x232 beam boundary", SNES_SUPERSCOPE_LATCH_CYCLES(232), 1024);
	Check("scope x255 beam hblank", SNES_SUPERSCOPE_LATCH_CYCLES(255), 1116);
}

static void CheckDMATimingMath()
{
	/* MesenCE aligns DMA ownership to the next multiple of 8 master clocks. */
	Check("DMA start sync @0", SnesDMAC::CalcStartSync(0), 8);
	Check("DMA start sync @2", SnesDMAC::CalcStartSync(2), 6);
	Check("DMA start sync @6", SnesDMAC::CalcStartSync(6), 2);
	Check("DMA start sync @8", SnesDMAC::CalcStartSync(8), 8);

	/* DMA resumes on the next boundary of the CPU clock that was paused. */
	Check("DMA end sync slow aligned", SnesDMAC::CalcEndSync(16, 8), 8);
	Check("DMA end sync slow +2", SnesDMAC::CalcEndSync(18, 8), 6);
	Check("DMA end sync fast +2", SnesDMAC::CalcEndSync(14, 6), 4);
	Check("DMA end sync xslow +4", SnesDMAC::CalcEndSync(20, 12), 4);
}

static void CheckDMARegisterMap()
{
	SnesDMAC dma;
	unsigned uChannel;

	dma.Reset();
	for (uChannel = 0; uChannel < SNESDMAC_CHANNEL_NUM; uChannel++)
	{
		unsigned uOffset;
		for (uOffset = 0; uOffset <= 0x0A; uOffset++)
			Check("DMA power-on register", dma.Read8(uChannel, uOffset, 0x43),
			      0xFF);
		Check("DMA $43xB power-on", dma.Read8(uChannel, 0x0B, 0x43), 0xFF);
		Check("DMA $43xF mirror", dma.Read8(uChannel, 0x0F, 0x43), 0xFF);
		Check("DMA $43xC open bus", dma.Read8(uChannel, 0x0C, 0x43), 0x43);
		Check("DMA $43xD open bus", dma.Read8(uChannel, 0x0D, 0x43), 0x43);
		Check("DMA $43xE open bus", dma.Read8(uChannel, 0x0E, 0x43), 0x43);

		for (uOffset = 0; uOffset <= 0x0B; uOffset++)
			dma.Write8(uChannel, uOffset,
			           (Uint8)(0x10u * uChannel + uOffset));
		for (uOffset = 0; uOffset <= 0x0B; uOffset++)
			Check("DMA register round trip", dma.Read8(uChannel, uOffset, 0x43),
			      0x10u * uChannel + uOffset);
		Check("DMA $43xB/$43xF storage mirror",
		      dma.Read8(uChannel, 0x0F, 0x43), 0x10u * uChannel + 0x0B);
	}
}

int main()
{
	CheckPowerOnRegisters();
	CheckTimedALU();
	CheckAutoJoypadTiming();
	CheckSpecialPeripherals();
	CheckScanlineTiming();
	CheckDMATimingMath();
	CheckDMARegisterMap();

	if (g_Failures)
	{
		std::printf("%d I/O register test(s) failed\n", g_Failures);
		return 1;
	}

	std::puts("I/O register tests passed");
	return 0;
}
