/*
 * Copyright (c) 1997-2004-2022 Icer Addis
 * Re-Worked By ReyFxck, Claude Aí, ChatGPT
 *
 * Description:
 *   Implements font behavior for shared base utilities.
 */

#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include "types.h"
#include "font.h"
#include "surface.h"
extern "C" {
#include "gs.h"
#include "gpprim.h"
#include "gskit_backend.h"
#include "gpfifo.h"

};

#define FIXED4(_x) ((Int32)((_x)*16.0f))
#define FIXED7(_x) ((Int32)((_x)*128.0f))

/* Integer pixel-doubling for crisp text.
 *
 * Higher modes use a non-integer logical transform (notably 2.5x in X).
 * Sampling the glyph atlas through it makes glyph shapes vary with screen
 * position. Draw glyphs directly in framebuffer space at an exact integer
 * scale: 1x in native 240p and 2x in the 480-line framebuffer modes.
 *
 * Layout still lives in the 256x240 logical space, so advances and
 * FontGetStrWidth convert the physical glyph size back to logical with
 * the SAME helper (_FontAdvLogical) -> centering/columns stay aligned. */
static inline Int32 _FontDrawScale(void)
{
    /* Round upward so integer glyph scaling remains crisp. */
    int n = (int)(GPPrimGetScaleY() + 0.999f);
    return (n < 1) ? 1 : n;
}
#define FONT_DRAW_SCALE (_FontDrawScale())

static inline Int32 _FontAdvLogical(Int32 physW)
{
    float sx = GPPrimGetScaleX();
    if (sx <= 0.0f) sx = 1.0f;
    return (Int32)(((float)physW) / sx + 0.5f);
}

extern unsigned char       _FontData_ui[];
extern const FontMapEntryT _FontMap_ui[];
extern const int           _FontMap_ui_count;
extern const int           _FontTex_ui_w;
extern const int           _FontTex_ui_h;
extern const int           _Font_ui_spacew;
extern const int           _Font_ui_lineh;
extern const int           _Font_ui_maxw;

/* ---- CJK dot-matrix font (generated by tools/font_gen_cjk.py) ----
 *
 * Native 16x16 HZK16 glyphs (no downsampling), stored as a bit-packed
 * source atlas in _CjkBits and uploaded as a 1024x1024 PSMT4 (4bpp)
 * atlas with a CT32 palette. Dots map to CLUT index 1 (alpha 0xFF) /
 * index 0 (transparent).
 *
 * PSMT4 is REQUIRED for the 480i VRAM budget: a PSMT8 atlas needs
 * 1 MiB of GS VRAM, which overflows the 4 MiB budget together with
 * the double-buffered 640x480 framebuffers (2.34 MiB), outTex,
 * cover and the blender - gsKit_vram_alloc then fails and the whole
 * app aborts at startup.  At 4bpp the atlas occupies 512 KiB and the
 * total stays at ~3.7 MiB.
 *
 * The 1bpp source data is expanded to 4bpp at FontInit time (two
 * texels per byte, low nibble = even/left column - the PS2 PSMT4
 * nibble order) into a .bss scratch buffer.
 *
 * gsKit upload/sampling both take TBW in 64-pixel units regardless
 * of the PSM (GS_SETREG_BITBLTBUF forwards it straight into DBW and
 * the GS BITBLT engine converts linear data into PSMT4 pages), so
 * the same pixel-based TBW used for PSMT8 works here as well.
 *
 * At 480i (FONT_DRAW_SCALE==2) glyphs are drawn 1:1 (16 texels ->
 * 16 pixels) for a crisp OPL-class result.  At 240p they are minified
 * 2:1; the CJK atlas is bound with LINEAR filtering so the GS averages
 * the 2x2 texel block (after CLUT lookup).
 *
 * gsKit re-loads the CLUT per primitive (TEX0 CLD=LOAD) and the vertex
 * RGBAQ does the tinting, so FontColor4f keeps working for Chinese. */
#define CJK_ATLAS_W    1024
#define CJK_ATLAS_H    1024
#define CJK_ATLAS_LOG2 10
#define CJK_GLYPH_SIZE 16
#define CJK_CELLS_ROW  64
#define CJK_ATLAS_PIXELS (CJK_ATLAS_W * CJK_ATLAS_H)
#define CJK_ATLAS_BYTES (CJK_ATLAS_W * CJK_ATLAS_H / 2)   /* 4bpp in VRAM */
#define CJK_TEX_TBP_OFFSET  (_FontTex_ui_w * _FontTex_ui_h * 4 / 256)
#define CJK_CLUT_TBP_OFFSET (CJK_TEX_TBP_OFFSET + CJK_ATLAS_BYTES / 256)

extern const unsigned short _CjkUcs[];
extern const unsigned char  _CjkBits[CJK_ATLAS_PIXELS / 8];
extern const unsigned int   _CjkClut[256];
extern const int            _CjkGlyphCount;

static TextureT _Font_CjkTex;
static Uint32   _Font_CjkTBP;
static Uint32   _Font_CjkClutTBP;
static Int32    _Font_CjkTofu;
static Bool     _Font_CjkReady = FALSE;

/* 4bpp repack scratch (DMA'd to VRAM, so keep it quadword-aligned). */
static Uint8    s_CjkPack[CJK_ATLAS_BYTES] _ALIGN(16);

/* Binary search over the sorted UCS table. -1 when missing. */
static Int32 _CjkFind(Uint32 ucp)
{
    Int32 lo = 0;
    Int32 hi = _CjkGlyphCount - 1;

    if (ucp > 0xFFFF) return -1;

    while (lo <= hi)
    {
        Int32 mid = (lo + hi) >> 1;

        if (_CjkUcs[mid] == ucp) return mid;
        if (_CjkUcs[mid] < ucp)  lo = mid + 1;
        else                     hi = mid - 1;
    }
    return -1;
}

/* Decode one UTF-8 codepoint.  Returns the pointer past it.  Invalid
 * sequences (stray continuation bytes, truncated tails) yield the raw
 * byte, which then renders as the tofu box.  Short-circuit evaluation
 * keeps every read inside the string (NUL never matches 0b10xxxxxx). */
static const Char *_FontNextCode(const Char *pStr, Uint32 *pCp)
{
    const unsigned char *p = (const unsigned char *)pStr;
    unsigned c = p[0];

    if (c < 0x80)
    {
        *pCp = c;
        return pStr + 1;
    }
    if ((c & 0xE0) == 0xC0 && (p[1] & 0xC0) == 0x80)
    {
        *pCp = ((c & 0x1Fu) << 6) | (p[1] & 0x3Fu);
        return pStr + 2;
    }
    if ((c & 0xF0) == 0xE0 && (p[1] & 0xC0) == 0x80 && (p[2] & 0xC0) == 0x80)
    {
        *pCp = ((c & 0x0Fu) << 12) | ((p[1] & 0x3Fu) << 6) | (p[2] & 0x3Fu);
        return pStr + 3;
    }
    if ((c & 0xF8) == 0xF0 &&
        (p[1] & 0xC0) == 0x80 && (p[2] & 0xC0) == 0x80 && (p[3] & 0xC0) == 0x80)
    {
        *pCp = ((c & 0x07u) << 18) | ((p[1] & 0x3Fu) << 12) |
               ((p[2] & 0x3Fu) << 6)  |  (p[3] & 0x3Fu);
        return pStr + 4;
    }

    *pCp = c;
    return pStr + 1;
}

struct FontStateT
{
    Uint32 uColor;
	Float32 vz;
	FontT   *pFont;
};

static FontStateT _Font_State;
static FontT _Font_Default;
static FontT _Font_Fixed;
static FontT *_Font_pFonts[4];

static Int32 _FontDrawChar(FontCharT *pFontChar, float fX, float fY, float z1, Uint32 uColor, int c)
{
	Uint32 u0,v0,u1,v1;
    Uint32 x0,y0,x1,y1;
    Int32 width, height;
    float sx, sy, px0, py0, px1, py1;

    width  = pFontChar->u1 - pFontChar->u0;
    height = pFontChar->v1 - pFontChar->v0;

    sx = GPPrimGetScaleX(); if (sx <= 0.0f) sx = 1.0f;
    sy = GPPrimGetScaleY(); if (sy <= 0.0f) sy = 1.0f;

    px0 = fX * sx + GPPrimGetOffsetX();
    py0 = fY * sy + GPPrimGetOffsetY();

    /*
     * At native 240p, place the source coordinates on texel centres and
     * finish the destination one GS subpixel after the final pixel centre.
     * This preserves every column of a 1:1 glyph without drawing a second
     * sprite over its right edge. UV and XY use 10.4/12.4 fixed point.
     */
    if (FONT_DRAW_SCALE == 1 && sx == 1.0f && sy == 1.0f)
    {
        u0 = (pFontChar->u0 << 4) + 8;  /* first texel centre */
        v0 = (pFontChar->v0 << 4) + 8;
        u1 = (pFontChar->u1 << 4) - 6;  /* 0.375 before the edge */
        v1 = (pFontChar->v1 << 4) - 6;

        px1 = px0 + (float)width  - 0.9375f;
        py1 = py0 + (float)height - 0.9375f;
    }
    else
    {
        /* Higher modes retain exact integer pixel scaling. */
        u0 = (pFontChar->u0 << 4);
        v0 = (pFontChar->v0 << 4);
        u1 = (pFontChar->u1 << 4);
        v1 = (pFontChar->v1 << 4);

        px1 = px0 + (float)(width  * FONT_DRAW_SCALE);
        py1 = py0 + (float)(height * FONT_DRAW_SCALE);
    }

    x0 = ((Uint32)FIXED4(px0)) & 0xFFFF;
    y0 = ((Uint32)FIXED4(py0)) & 0xFFFF;
    x1 = ((Uint32)FIXED4(px1)) & 0xFFFF;
    y1 = ((Uint32)FIXED4(py1)) & 0xFFFF;

	GPPrimTexRectAbs(x0, y0, u0, v0, x1, y1, u1, v1, 10, uColor, 1);

    /* advance in LOGICAL units: physical glyph width + 2px gap */
    return _FontAdvLogical(width * FONT_DRAW_SCALE + 2);

}

/* Bind the CJK PSMT4 atlas + resident VRAM palette.  gsKit emits TEX0
   with CBP/CPSM and CLD=LOAD per primitive, so the palette is fetched
   from VRAM without any per-frame upload.  LINEAR filtering: at 1:1
   sampling lands on texel centres (no blur), while the 240p 2:1 minify
   gets proper 2x2 averaging (the GS filters after CLUT lookup). */
static void _FontBindCjk(void)
{
    GPPrimSetTex(_Font_CjkTBP, CJK_ATLAS_W, CJK_ATLAS_LOG2, CJK_ATLAS_LOG2,
                 GS_PSMT4, _Font_CjkClutTBP, 0, GS_PSMCT32, 1);
}

/* Draw one 16x16 CJK glyph (atlas cell of glyph index iGlyph) at the
   logical position.  At 480i the glyph maps 1:1 texel->pixel (crisp
   HZK16 dot matrix); at 240p it is minified 2:1 with LINEAR sampling.
   Returns the logical advance (full-width slot, no gap). */
static Int32 _FontDrawCharCJK(Int32 iGlyph, float fX, float fY, Uint32 uColor)
{
    Uint32 u0, v0, u1, v1;
    Uint32 x0, y0, x1, y1;
    float sx, sy, px0, py0, px1, py1;
    Int32 tu, tv;
    Int32 disp;                 /* on-screen glyph size, physical pixels */

    tu = (iGlyph % CJK_CELLS_ROW) * CJK_GLYPH_SIZE;
    tv = (iGlyph / CJK_CELLS_ROW) * CJK_GLYPH_SIZE;

    sx = GPPrimGetScaleX(); if (sx <= 0.0f) sx = 1.0f;
    sy = GPPrimGetScaleY(); if (sy <= 0.0f) sy = 1.0f;

    px0 = fX * sx + GPPrimGetOffsetX();
    py0 = fY * sy + GPPrimGetOffsetY();

    /* Snap the origin to whole device pixels.  At 480i sx/sy are 2.5, so
       the raw origin is fractional and the GS (which interpolates ST from
       the sprite corner) would sample exactly on texel BOUNDARIES; with
       LINEAR filtering every column then blends 50/50 with its neighbour
       and each hanzi renders as a ghosted, unrecognisable shape.  After
       the snap the 1:1 path samples texel centres (crisp) and the 240p
       2:1 minify samples exact edges (clean 2x2 average).  The at most
       0.5px position shift is invisible. */
    px0 = (float)((Int32)(px0 + 0.5f));
    py0 = (float)((Int32)(py0 + 0.5f));

    /* 480i(2x): 16x16 texels -> 16x16 px = native 1:1.
       240p(1x): 16x16 texels -> 8x8 px (2:1, LINEAR-averaged). */
    disp = CJK_GLYPH_SIZE * FONT_DRAW_SCALE / 2;

    if (disp == CJK_GLYPH_SIZE)
    {
        /* Exact 1:1 over a snapped-integer origin.  The GS evaluates the
           interpolated UV at each pixel centre (x = x0 + k + 0.5), so to
           land sample k on the centre of texel tu+k the UV at the sprite
           edge must be the CELL EDGE (tu), NOT texel-centre (tu+0.5):
           adding the half-texel (+8) used to push every sample exactly
           onto a texel BOUNDARY, where LINEAR blends 50/50 with the
           neighbouring column and each hanzi renders as a ghosted,
           unrecognisable "wrong character".  Endpoint -15 keeps the UV
           slope at exactly 1.0 over the 15.0625 px span. */
        u0 = (tu << 4);
        v0 = (tv << 4);
        u1 = ((tu + CJK_GLYPH_SIZE) << 4) - 15;
        v1 = ((tv + CJK_GLYPH_SIZE) << 4) - 15;

        px1 = px0 + (float)CJK_GLYPH_SIZE - 0.9375f;
        py1 = py0 + (float)CJK_GLYPH_SIZE - 0.9375f;
    }
    else
    {
        /* Minify / integer upscale: plain texel->pixel mapping. */
        u0 = (tu << 4);
        v0 = (tv << 4);
        u1 = ((tu + CJK_GLYPH_SIZE) << 4);
        v1 = ((tv + CJK_GLYPH_SIZE) << 4);

        px1 = px0 + (float)disp;
        py1 = py0 + (float)disp;
    }

    x0 = ((Uint32)FIXED4(px0)) & 0xFFFF;
    y0 = ((Uint32)FIXED4(py0)) & 0xFFFF;
    x1 = ((Uint32)FIXED4(px1)) & 0xFFFF;
    y1 = ((Uint32)FIXED4(py1)) & 0xFFFF;

    GPPrimTexRectAbs(x0, y0, u0, v0, x1, y1, u1, v1, 10, uColor, 1);

    return _FontAdvLogical(disp);
}

Int32 FontGetStrWidth(const Char *pStr)
{
    Int32 iWidth = 0;
	FontT *pFont;
	pFont = _Font_State.pFont;
	if (!pFont) return 0;

    while (*pStr)
    {
        Uint32 cp;
        pStr = _FontNextCode(pStr, &cp);

        if (cp < 128)
        {
            if (cp != ' ')
            {
                FontCharT *pFontChar = &pFont->CharMap[cp];
                iWidth += _FontAdvLogical((pFontChar->u1 - pFontChar->u0) * FONT_DRAW_SCALE + 2);
            }
            else
            {
                // space
                iWidth += _FontAdvLogical(pFont->uCharX * FONT_DRAW_SCALE);
            }
        }
        else
        {
            /* CJK / unknown byte: full-width slot.  Monospace fonts
               advance two ASCII cells per hanzi; proportional fonts
               advance the on-screen glyph size. */
            Int32 adv = (pFont->uFixedWidth)
                        ? pFont->uFixedWidth * 2 * FONT_DRAW_SCALE
                        : CJK_GLYPH_SIZE * FONT_DRAW_SCALE / 2;
            iWidth += _FontAdvLogical(adv);
        }
    }
	return iWidth;
}


static void _FontDrawStr(FontT *pFont, Float32 vx, Float32 vy, Float32 vz, const Char *pStr, Uint32 uColor)
{
    TextureT *pTexture = &pFont->Texture;
    if (!pTexture) return;

    /* Bind ASCII atlas for the leading run; rebind on every CJK->ASCII
       transition so mixed text (e.g. "中文.sfc") renders correctly. */
    GPPrimSetTex(pTexture->uVramAddr, pTexture->uWidth,
                 pTexture->uWidthLog2, pTexture->uHeightLog2,
                 pTexture->eFormat, 0, 0, 0, 0);
    int bCjkBound = 0;

	while (*pStr)
	{
        Uint32 cp;
        pStr = _FontNextCode(pStr, &cp);

        if (cp < 128)
        {
            /* Re-bind ASCII atlas if we were on CJK (fixes garbled
               English/symbols after Chinese text). */
            if (bCjkBound)
            {
                GPPrimSetTex(pTexture->uVramAddr, pTexture->uWidth,
                             pTexture->uWidthLog2, pTexture->uHeightLog2,
                             pTexture->eFormat, 0, 0, 0, 0);
                bCjkBound = 0;
            }

            if (cp != ' ')
            {
                FontCharT *pFontChar = &pFont->CharMap[cp];
                Int32 iWidth;

                iWidth = _FontDrawChar(pFontChar, vx, vy, vz, uColor, (int)cp);

                if (pFont->uFixedWidth) iWidth = _FontAdvLogical((Int32)pFont->uFixedWidth * FONT_DRAW_SCALE);
			    vx += iWidth;
            }
            else
            {
		        vx += _FontAdvLogical(pFont->uCharX * FONT_DRAW_SCALE);
            }
        }
        else if (_Font_CjkReady)
        {
            Int32 iGlyph = _CjkFind(cp);
            if (iGlyph < 0) iGlyph = _Font_CjkTofu;    /* tofu box */
            if (iGlyph >= 0)
            {
                Int32 iWidth;

                _FontBindCjk();
                bCjkBound = 1;
                iWidth = _FontDrawCharCJK(iGlyph, vx, vy, uColor);

                /* CJK full-width slot advance */
                if (pFont->uFixedWidth)
                    iWidth = _FontAdvLogical((Int32)pFont->uFixedWidth * 2 * FONT_DRAW_SCALE);
                vx += iWidth;
            }
        }
        else
        {
            /* CJK data unavailable: still reserve a full-width slot so
               layout stays consistent. */
            vx += _FontAdvLogical(CJK_GLYPH_SIZE * FONT_DRAW_SCALE / 2);
        }
	}
}

static void _FontSetCharMap(FontT *pFont, Uint8 uChar, Uint32 u, Uint32 v, Uint32 w, Uint32 h)
{
	pFont->CharMap[uChar].u0 = u;
	pFont->CharMap[uChar].v0 = v;
	pFont->CharMap[uChar].u1 = u + w;
	pFont->CharMap[uChar].v1 = v + h;
}

static void _FontSetCharSize(FontT *pFont, Uint32 w, Uint32 h)
{
	pFont->uCharX = w;
	pFont->uCharY = h;
}

/*
static void _FontBiosMake(FontT *pFont)
{
	int x, y;

	TextureNew(&pFont->Texture, vixar_width, vixar_height, GS_PSMT8);
    TextureSetAddr(&pFont->Texture, FONT_TEX);

	_FontSetCharSize(pFont, 8, 12);

	for (y=0; y<8; y++) {
		for (x=0; x<16; x++)
		{
            Uint8 uChar  = y * 16 + x;
			_FontSetCharMap(pFont, uChar, x * 16, y * 16, vixarmet[uChar], 16);
		}
	}

	gp_uploadTexture(&thegp, FONT_TEX, 256, 0, 0, GS_PSMT8, vixar_image, vixar_width, vixar_height);
	gp_uploadTexture(&thegp, FONT_CLUT, 256, 0, 0, GS_PSMCT16, vixar_clut, 256, 1);
	gp_hardflush(&thegp);
}
  */

void FontMake(FontT *pFont, CSurface *pSurface, Uint32 uVramAddr, const Char *pCharList)
{
    TextureT *pTexture = &pFont->Texture;

    FontNew(pFont);
    FontParseChars(pFont, pSurface, pCharList);

    // allocate texture in GS Memory
    TextureNew(pTexture, pSurface->GetWidth(), pSurface->GetHeight(), GS_PSMCT32);
    TextureSetAddr(pTexture, uVramAddr);

    // upload texture data to memory
    TextureUpload(pTexture,  pSurface->GetLinePtr(0));
    GPFifoFlush();
}

void FontMakeFromMap(FontT *pFont, CSurface *pSurface, Uint32 uVramAddr,
                     const FontMapEntryT *pMap, Int32 nCount,
                     Int32 uSpaceW, Int32 uLineH)
{
    TextureT *pTexture = &pFont->Texture;
    Int32 i;

    FontNew(pFont);

    // explicit glyph map (no auto-parse)
    for (i = 0; i < nCount; i++)
        _FontSetCharMap(pFont, (Uint8)pMap[i].c,
                        pMap[i].u, pMap[i].v, pMap[i].w, pMap[i].h);

    _FontSetCharSize(pFont, uSpaceW, uLineH);

    // allocate + upload the atlas (same as FontMake)
    TextureNew(pTexture, pSurface->GetWidth(), pSurface->GetHeight(), GS_PSMCT32);
    TextureSetAddr(pTexture, uVramAddr);
    TextureUpload(pTexture, pSurface->GetLinePtr(0));
    GPFifoFlush();
}


void FontColor4f(Float32 r, Float32 g, Float32 b, Float32 a)
{
    Uint32 uR, uG, uB, uA;

    /* Tint all "white" text amber/gold (user preference).  Any request
       for pure white (1,1,1) is remapped to a warm gold; every other
       colour (cyan headers, green, red, ...) passes through untouched.
       Centralising it here recolours white text on ALL screens at once. */
    if (r >= 1.0f && g >= 1.0f && b >= 1.0f)
    {
        r = 1.00f; g = 0.88f; b = 0.46f;
    }

    uR = FIXED7(r);
    uG = FIXED7(g);
    uB = FIXED7(b);
    uA = FIXED7(a);

	_Font_State.uColor = GS_SET_RGBA(uR, uG, uB, uA);

}

void FontPuts(Float32 vx, Float32 vy, const Char *pStr)
{
	FontT *pFont;
	pFont = _Font_State.pFont;
	if (!pFont) return;

	_FontDrawStr(pFont,
				vx, vy, 15.0f,
				pStr,
				_Font_State.uColor
				);

}

void FontPrintf(Float32 vx, Float32 vy, const Char *pFormat, ...)
{
	static char strbuf[1024];
	va_list args;

	va_start(args, pFormat);
	vsprintf(strbuf, pFormat, args);
	va_end(args);

	FontPuts(vx,vy,strbuf);
}

void FontSelect(Int32 iFont)
{
	_Font_State.pFont = _Font_pFonts[iFont];
}


void FontSetFont(Int32 iFont, FontT *pFont)
{
    _Font_pFonts[iFont] = pFont;
}


Int32 FontGetWidth()
{
	return _Font_State.pFont ? _Font_State.pFont->uCharX : 0;
}

Int32 FontGetHeight()
{
	return _Font_State.pFont ? _Font_State.pFont->uCharY : 0;
}


Uint32 FontGetVramSize()
{
    /* One block: UI RGBA8 atlas | CJK PSMT4 atlas | palette page.
       Both sub-offsets are 256B-aligned so CBP/CBP stay valid no matter
       where the video backend places the block. */
    return (Uint32)_FontTex_ui_w * (Uint32)_FontTex_ui_h * 4U   /* UI atlas */
         + CJK_ATLAS_BYTES                                      /* CJK atlas */
         + 8192U;                                               /* palette   */
}


void FontInit(Uint32 uVramAddr)
{
    CSurface Surface;

    // UI font (m5x7, Daniel Linssen): embedded RGBA8 atlas + explicit map.
    Surface.Set(_FontData_ui, _FontTex_ui_w, _FontTex_ui_h,
                _FontTex_ui_w * 4, PixelFormatGetByEnum(PIXELFORMAT_RGBA8));

    FontMakeFromMap(&_Font_Default, &Surface, uVramAddr,
                    _FontMap_ui, _FontMap_ui_count,
                    _Font_ui_spacew, _Font_ui_lineh);

    FontMakeFromMap(&_Font_Fixed, &Surface, uVramAddr,
                    _FontMap_ui, _FontMap_ui_count,
                    _Font_ui_spacew, _Font_ui_lineh);

    /* monospace cell = widest glyph so nothing overlaps in fixed mode */
    _Font_Fixed.uFixedWidth = _Font_ui_maxw;

    FontSetFont(0, &_Font_Default);
    FontSetFont(1, &_Font_Fixed);
    FontSetFont(2, &_Font_Default);
    FontSetFont(3, &_Font_Default);

	FontSelect(0);
	FontColor4f(1.0f, 1.0f, 1.0f, 1.0f);

    /* CJK atlas + resident palette live in the same allocation, right
       after the UI atlas (see FontGetVramSize). */
    _Font_CjkTBP     = uVramAddr + CJK_TEX_TBP_OFFSET;
    _Font_CjkClutTBP = uVramAddr + CJK_CLUT_TBP_OFFSET;

    TextureNew(&_Font_CjkTex, CJK_ATLAS_W, CJK_ATLAS_H, GS_PSMT4);
    TextureSetAddr(&_Font_CjkTex, _Font_CjkTBP);

    /* Expand the committed 1bpp source atlas directly to the exact PSMT4
       byte stream expected by the anyi renderer.  This keeps the same
       1024x1024 atlas/cell layout while avoiding a 5.4 MB generated C++
       source file. */
    {
        Uint32 i;
        for (i = 0; i < CJK_ATLAS_BYTES; i++)
        {
            Uint32 p0 = 2U * i;
            Uint32 p1 = p0 + 1U;
            Uint8 a = (Uint8)((_CjkBits[p0 >> 3] >> (7U - (p0 & 7U))) & 1U);
            Uint8 b = (Uint8)((_CjkBits[p1 >> 3] >> (7U - (p1 & 7U))) & 1U);
            s_CjkPack[i] = (Uint8)(a | (b << 4));
        }
    }

    /* Upload the 1024x1024 PSMT4 atlas as 256-line strips (128 KB each).
       gsKit's send helper takes the TBW in 64-pixel units regardless of
       the PSM and the GS BITBLT engine converts the linear stream into
       PSMT4 pages automatically. */
    {
        const Uint32 stripH     = 256;
        const Uint32 stripBytes = CJK_ATLAS_W * stripH / 2U;
        Uint32 i;
        for (i = 0; i * stripH < (Uint32)CJK_ATLAS_H; i++)
        {
            GPPrimUploadTexture(_Font_CjkTBP + i * (stripBytes / 256),
                                CJK_ATLAS_W, 0, 0, GS_PSMT4,
                                (void *)((Uint8 *)s_CjkPack + i * stripBytes),
                                CJK_ATLAS_W, stripH);
        }
    }

    /* 256-entry CT32 palette (1024 bytes) as a 256x1 image.  PSMT4 only
       indexes the first 16 entries (CSA=0); the remaining entries are
       harmless slack inside the reserved palette page. */
    GPPrimUploadTexture(_Font_CjkClutTBP, 256, 0, 0, GS_PSMCT32,
                        (void *)_CjkClut, 256, 1);

    _Font_CjkTofu   = _CjkFind(0x25A1);
    _Font_CjkReady  = (_Font_CjkTofu >= 0) ? TRUE : FALSE;
}

void FontShutdown()
{
	FontDelete(&_Font_Default);
	FontDelete(&_Font_Fixed);
}



//
//
//




void FontNew(FontT *pFont)
{
//    pFont->pTexture = NULL;
//    pFont->pClut    = NULL;
    pFont->nChars   = 0;
    pFont->uFixedWidth = 0;
    memset(&pFont->CharMap, 0, sizeof(pFont->CharMap));
}

void FontDelete(FontT *pFont)
{
//    pFont->pTexture=NULL;
}

static Bool _FontScanHorizWhite(CSurface *pSurface, Uint32 uStartX, Uint32 uEndX, Uint32 uY)
{
    Uint32 uX;
    Uint32 *pLine;
    pLine = (Uint32 *)pSurface->GetLinePtr(uY);
    if (!pLine) return TRUE;

    for (uX = uStartX; uX < uEndX; uX++)
    {
        if (pLine[uX] & 0xFF000000)
        {
            return FALSE;
        }
    }

    return TRUE;
}

static Bool _FontScanVertWhite(CSurface *pSurface, Uint32 uStartY, Uint32 uEndY, Uint32 uX)
{
    Uint32 uY;
    Uint32 *pLine;

    for (uY = uStartY; uY < uEndY; uY++)
    {
        pLine = (Uint32 *)pSurface->GetLinePtr(uY);
        if (!pLine) return TRUE;

        if (pLine[uX] & 0xFF000000)
        {
            return FALSE;
        }
    }

    return TRUE;
}

const Char *_FontParseLine(FontT *pFont, CSurface *pSurface, const Char *pCharList, Uint32 uStartY, Uint32 uEndY)
{
    Uint32 uX;
    Uint32 uWidth;//, uHeight;

    uWidth = pSurface->GetWidth();
    //uHeight = pSurface->GetHeight();

    uX = 0;
    while (uX < uWidth)
    {
        Uint32 uStartX, uEndX;

        // scan for non-white space
        while ((uX < uWidth) && _FontScanVertWhite(pSurface, uStartY, uEndY, uX))
        {
            uX++;
        }

        if (uX < uWidth)
        {

            // get start of char
            uStartX = uX;

            // scan for white space
            while ((uX < uWidth) && !_FontScanVertWhite(pSurface, uStartY, uEndY, uX))
            {
                uX++;
            }

            // get end of char
            uEndX = uX;

            _FontSetCharMap(pFont, *pCharList,  uStartX, uStartY, uEndX - uStartX, uEndY - uStartY);
            pCharList++;

//            printf("char %d,%d -> %d,%d\n", uStartX, uStartY, uEndX, uEndY);
            uX++;
        }

    }

    return pCharList;
}

void FontParseChars(FontT *pFont, CSurface *pSurface, const Char *pCharList)
{
    Uint32 uY;
    Uint32 uWidth, uHeight;
    Uint32 uFontHeight = 0;

    uWidth = pSurface->GetWidth();
    uHeight = pSurface->GetHeight();

    uY=0;
    while (uY < uHeight)
    {
        Uint32 uStartY, uEndY;
        // scan for non-white space
        while ((uY < uHeight) && _FontScanHorizWhite(pSurface, 0, uWidth, uY))
        {
            uY++;
        }

        if (uY < uHeight)
        {

            // get start of line
            uStartY = uY;

            // scan for white space
            while ((uY < uHeight) && !_FontScanHorizWhite(pSurface, 0, uWidth, uY))
            {
                uY++;
            }

            uEndY = uY;

            if (uFontHeight == 0)
            {
                // font height is height of first line
                uFontHeight = uEndY - uStartY;
            }

            pCharList = _FontParseLine(pFont, pSurface, pCharList, uStartY, uEndY);
            uY++;
        }
    }

	_FontSetCharSize(pFont, 5, uFontHeight);

}
